# fly.toml app configuration file generated for camino-al-gym-backend on 2025-12-13T13:49:33-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'camino-al-gym-backend'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = 'true'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = 'sqlite_data'
  destination = '/app/data'

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
